/*
 * Ventus TMA v2 constants used by the Spike ISA model.
 * This file is maintained independently in the Spike project.
 */
#ifndef SPIKE_VENTUS_TMA_V2_SPEC_H
#define SPIKE_VENTUS_TMA_V2_SPEC_H

#include <stdint.h>

#define VENTUS_TMA_V2_DESCRIPTOR_STORAGE_BYTES 128u
#define VENTUS_TMA_V2_DESCRIPTOR_ALIGNMENT 128u
#define VENTUS_TMA_V2_MAGIC UINT32_C(0x544d4103)
#define VENTUS_TMA_V2_WORD_MAGIC 0u
#define VENTUS_TMA_V2_WORD_CONTROL 1u
#define VENTUS_TMA_V2_WORD_GLOBAL_BASE 2u
#define VENTUS_TMA_V2_WORD_GLOBAL_DIMS 4u
#define VENTUS_TMA_V2_WORD_GLOBAL_STRIDES 9u
#define VENTUS_TMA_V2_WORD_BOX_DIMS 17u
#define VENTUS_TMA_V2_WORD_ELEMENT_STRIDES 22u
#define VENTUS_TMA_V2_RANK_MAX 5u
#define VENTUS_TMA_V2_ATOM_BYTES 16u
#define VENTUS_TMA_V2_LINE_BYTES 128u
/*
 * Payload translations live only for one TMA command. Software must not
 * remap, unmap, migrate a touched page, or recycle its ASID until the
 * command completion (including mbarrier/group acknowledgement) is visible.
 */
#define VENTUS_TMA_V2_OPCODE 0x42u
#define VENTUS_TMA_V2_FUNCT_BULK_G2S 1u
#define VENTUS_TMA_V2_FUNCT_TENSOR_G2S 2u
#define VENTUS_TMA_V2_FUNCT_BULK_S2G 3u
#define VENTUS_TMA_V2_FUNCT_TENSOR_S2G 4u
#define VENTUS_TMA_V2_FUNCT_PREFETCH_TENSORMAP 5u
#define VENTUS_TMA_V2_TENSORMAP_PREFETCH 0u
#define VENTUS_TMA_V2_TENSORMAP_INVALIDATE 1u
#define VENTUS_TMA_V2_FUNCT_S2G_GROUP 6u
#define VENTUS_TMA_V2_FUNCT_MBARRIER_PROXY 7u
#define VENTUS_TMA_V2_S2G_GROUP_COMMIT 16u
#define VENTUS_TMA_V2_S2G_GROUP_WAIT_BASE 24u
#define VENTUS_TMA_V2_S2G_GROUP_WAIT_KEEP_MAX 3u
#define VENTUS_TMA_V2_MBARRIER_INIT 0u
#define VENTUS_TMA_V2_MBARRIER_ARRIVE_EXPECT_TX 1u
#define VENTUS_TMA_V2_MBARRIER_WAIT 2u
#define VENTUS_TMA_V2_FENCE_PROXY_ASYNC_SHARED 3u
#define VENTUS_TMA_V2_STATUS_CSR 0x814u
#define VENTUS_TMA_V2_S2G_GROUPS_PER_WARP 4u
#define VENTUS_TMA_V2_MBARRIER_ENTRIES_PER_WG 4u
#define VENTUS_TMA_V2_MBARRIER_ENTRIES VENTUS_TMA_V2_MBARRIER_ENTRIES_PER_WG
#define VENTUS_TMA_V2_MBARRIER_BYTES 8u
#define VENTUS_TMA_V2_MBARRIER_ALIGNMENT 8u
#define VENTUS_TMA_V2_REDUCE_COPY 0u
#define VENTUS_TMA_V2_REDUCE_ADD 1u
#define VENTUS_TMA_V2_REDUCE_MIN 2u
#define VENTUS_TMA_V2_REDUCE_MAX 3u
#define VENTUS_TMA_V2_REDUCE_AND 4u
#define VENTUS_TMA_V2_REDUCE_OR 5u
#define VENTUS_TMA_V2_REDUCE_XOR 6u
#define VENTUS_TMA_V2_REDUCE_RESERVED 7u
#define VENTUS_TMA_V2_BULK_REDUCE_TYPE_U32 0u
#define VENTUS_TMA_V2_BULK_REDUCE_TYPE_S32 1u
#define VENTUS_TMA_V2_BULK_REDUCE_TYPE_B32 2u
#define VENTUS_TMA_V2_BULK_REDUCE_TYPE_RESERVED 3u
#define VENTUS_TMA_V2_REDUCE_ATOMIC 1u
#define VENTUS_TMA_V2_REDUCE_REQUIRES_EXCLUSIVE_DESTINATION 0u

enum ventus_tma_v2_status_code {
  VENTUS_TMA_STATUS_OK = 0,
  VENTUS_TMA_STATUS_INVALID_DESCRIPTOR = 1,
  VENTUS_TMA_STATUS_UNSUPPORTED_FEATURE = 2,
  VENTUS_TMA_STATUS_ADDRESS_OVERFLOW = 3,
  VENTUS_TMA_STATUS_MBARRIER_PROTOCOL = 4,
  VENTUS_TMA_STATUS_INVALID_GROUP_OPERATION = 5
};

enum ventus_tma_v2_direction {
  VENTUS_TMA_G2S = 0,
  VENTUS_TMA_S2G = 1
};

enum ventus_tma_v2_dtype {
  VENTUS_TMA_DTYPE_U8 = 0,
  VENTUS_TMA_DTYPE_U16 = 1,
  VENTUS_TMA_DTYPE_U32 = 2,
  VENTUS_TMA_DTYPE_S32 = 3,
  VENTUS_TMA_DTYPE_U64 = 4,
  VENTUS_TMA_DTYPE_S64 = 5,
  VENTUS_TMA_DTYPE_FP16 = 6,
  VENTUS_TMA_DTYPE_FP32 = 7,
  VENTUS_TMA_DTYPE_FP32_FTZ = 8,
  VENTUS_TMA_DTYPE_FP64 = 9,
  VENTUS_TMA_DTYPE_BF16 = 10,
  VENTUS_TMA_DTYPE_TF32 = 11,
  VENTUS_TMA_DTYPE_TF32_FTZ = 12,
  VENTUS_TMA_DTYPE_B4X16 = 13,
  VENTUS_TMA_DTYPE_B4X16_P64 = 14,
  VENTUS_TMA_DTYPE_B6 = 15,
};

enum ventus_tma_v2_interleave {
  VENTUS_TMA_INTERLEAVE_NONE = 0,
  VENTUS_TMA_INTERLEAVE_16B = 1,
  VENTUS_TMA_INTERLEAVE_32B = 2
};

enum ventus_tma_v2_swizzle {
  VENTUS_TMA_SWIZZLE_NONE = 0,
  VENTUS_TMA_SWIZZLE_32B = 1,
  VENTUS_TMA_SWIZZLE_64B = 2,
  VENTUS_TMA_SWIZZLE_128B = 3,
  VENTUS_TMA_SWIZZLE_96B = 4
};

enum ventus_tma_v2_swizzle_atomicity {
  VENTUS_TMA_SWIZZLE_ATOM_16B = 0,
  VENTUS_TMA_SWIZZLE_ATOM_32B = 1,
  VENTUS_TMA_SWIZZLE_ATOM_32B_FLIP_8B = 2,
  VENTUS_TMA_SWIZZLE_ATOM_64B = 3
};

enum ventus_tma_v2_oob_fill {
  VENTUS_TMA_OOB_ZERO = 0,
  VENTUS_TMA_OOB_NAN = 1
};

#endif
